#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;

namespace AetherNexus.UIWidgets.Editor.UIRefBinder
{
	internal readonly struct NewFieldSpec
	{
		/// <summary>Fully-qualified type name, so the inserted line compiles regardless of the
		/// target script's existing using directives.</summary>
		public readonly string qualifiedTypeName;
		public readonly string fieldName;

		public NewFieldSpec(string qualifiedTypeName, string fieldName)
		{
			this.qualifiedTypeName = qualifiedTypeName;
			this.fieldName = fieldName;
		}
	}

	/// <summary>
	/// Writes [SerializeField] declarations into a marked region inside an existing script's class
	/// body, creating the region on first use. Everything else in the file is left untouched. Rebuilds
	/// the region's field list from scratch on every write (existing declarations merged with the
	/// incoming ones, collapsing same-name duplicates to one line) rather than appending, so this can
	/// never emit two declarations with the same name — regardless of what the caller passes in or
	/// what state the region was already in (e.g. duplicates left over from an earlier bug).
	/// </summary>
	internal static class ScriptFieldWriter
	{
		private const string RegionStart = "\t\t// <AUTO-GENERATED FIELDS START>";
		private const string RegionEnd = "\t\t// <AUTO-GENERATED FIELDS END>";
		private static readonly Regex ClassOpenBrace = new Regex(@"class\s+\w+[^\{]*\{", RegexOptions.Singleline);

		// Mirrors ScriptFieldScanner.FieldRegex's shape, scoped only to the auto-gen region's own text.
		private static readonly Regex ExistingFieldLineRegex = new Regex(
			@"\[SerializeField\]\s*(?:private\s+|protected\s+|public\s+|internal\s+)?" +
			@"(?<type>[A-Za-z_][A-Za-z0-9_.]*)\s+(?<name>[A-Za-z_][A-Za-z0-9_]*)\s*(?:=[^;]+)?;",
			RegexOptions.Compiled);

		internal static bool TryInsertFields(string scriptAssetPath, IReadOnlyList<NewFieldSpec> newFields, out string error)
		{
			error = null;
			if (newFields == null || newFields.Count == 0)
				return true;

			string fullPath = Path.GetFullPath(scriptAssetPath);
			if (!File.Exists(fullPath))
			{
				error = $"Script not found on disk: {scriptAssetPath}";
				return false;
			}

			string text = File.ReadAllText(fullPath);

			int regionStartIndex = text.IndexOf(RegionStart, StringComparison.Ordinal);
			int regionEndIndex = text.IndexOf(RegionEnd, StringComparison.Ordinal);
			bool hasRegion = regionStartIndex >= 0 && regionEndIndex > regionStartIndex;

			// Merge existing region declarations with the incoming ones into a single ordered,
			// name-deduplicated map. A later occurrence of a name always wins — this is what collapses
			// any already-accumulated duplicate lines down to one, and lets a requested bind's type
			// override whatever the region previously held for that name.
			var order = new List<string>();
			var typeByName = new Dictionary<string, string>();

			if (hasRegion)
			{
				int contentStart = regionStartIndex + RegionStart.Length;
				string existingRegion = text.Substring(contentStart, regionEndIndex - contentStart);
				foreach (Match m in ExistingFieldLineRegex.Matches(existingRegion))
				{
					string name = m.Groups["name"].Value;
					if (!typeByName.ContainsKey(name))
						order.Add(name);
					typeByName[name] = m.Groups["type"].Value;
				}
			}

			foreach (var f in newFields)
			{
				if (string.IsNullOrEmpty(f.fieldName))
					continue;
				if (!typeByName.ContainsKey(f.fieldName))
					order.Add(f.fieldName);
				typeByName[f.fieldName] = f.qualifiedTypeName;
			}

			var fieldLines = new StringBuilder();
			foreach (var name in order)
				fieldLines.Append("\t\t[SerializeField] private ").Append(typeByName[name]).Append(' ').Append(name).Append(";\n");

			string newText;
			if (hasRegion)
			{
				int contentStart = regionStartIndex + RegionStart.Length;
				newText = text.Substring(0, contentStart) + "\n" + fieldLines + text.Substring(regionEndIndex);
			}
			else
			{
				var classMatch = ClassOpenBrace.Match(text);
				if (!classMatch.Success)
				{
					error = "Could not find a class declaration to insert fields into.";
					return false;
				}

				int insertAt = classMatch.Index + classMatch.Length;
				string block = "\n" + RegionStart + "\n" + fieldLines + RegionEnd + "\n";
				newText = text.Substring(0, insertAt) + block + text.Substring(insertAt);
			}

			File.WriteAllText(fullPath, newText);
			AssetDatabase.ImportAsset(scriptAssetPath);
			return true;
		}
	}
}
#endif
