#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;

namespace AetherNexus.UIWidgets.Editor.UIRefBinder
{
	internal readonly struct NewFieldSpec
	{
		/// <summary>Fully-qualified type name, so the inserted line compiles regardless of the
		/// target script's existing using directives.</summary>
		public readonly string qualifiedTypeName;
		public readonly string fieldName;

		public NewFieldSpec(string qualifiedTypeName, string fieldName)
		{
			this.qualifiedTypeName = qualifiedTypeName;
			this.fieldName = fieldName;
		}
	}

	/// <summary>
	/// Inserts new [SerializeField] declarations into a marked region inside an existing script's
	/// class body, creating the region on first use. Everything else in the file is left untouched.
	/// </summary>
	internal static class ScriptFieldWriter
	{
		private const string RegionStart = "\t\t// <AUTO-GENERATED FIELDS START>";
		private const string RegionEnd = "\t\t// <AUTO-GENERATED FIELDS END>";
		private static readonly Regex ClassOpenBrace = new Regex(@"class\s+\w+[^\{]*\{", RegexOptions.Singleline);

		internal static bool TryInsertFields(string scriptAssetPath, IReadOnlyList<NewFieldSpec> newFields, out string error)
		{
			error = null;
			if (newFields == null || newFields.Count == 0)
				return true;

			string fullPath = Path.GetFullPath(scriptAssetPath);
			if (!File.Exists(fullPath))
			{
				error = $"Script not found on disk: {scriptAssetPath}";
				return false;
			}

			string text = File.ReadAllText(fullPath);

			var fieldLines = new StringBuilder();
			foreach (var f in newFields)
				fieldLines.Append("\t\t[SerializeField] private ").Append(f.qualifiedTypeName).Append(' ').Append(f.fieldName).Append(";\n");

			string newText;
			int regionEndIndex = text.IndexOf(RegionEnd, StringComparison.Ordinal);
			if (regionEndIndex >= 0)
			{
				newText = text.Substring(0, regionEndIndex) + fieldLines + text.Substring(regionEndIndex);
			}
			else
			{
				var classMatch = ClassOpenBrace.Match(text);
				if (!classMatch.Success)
				{
					error = "Could not find a class declaration to insert fields into.";
					return false;
				}

				int insertAt = classMatch.Index + classMatch.Length;
				string block = "\n" + RegionStart + "\n" + fieldLines + RegionEnd + "\n";
				newText = text.Substring(0, insertAt) + block + text.Substring(insertAt);
			}

			File.WriteAllText(fullPath, newText);
			AssetDatabase.ImportAsset(scriptAssetPath);
			return true;
		}
	}
}
#endif
